routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|-----------------
|   Web-Site
|-----------------
*/
Route::get('/', 'PagesController@getHome');
Route::get('/contact', 'PagesController@getContact');
Route::get('/about', 'PagesController@getAbout');
Route::get('/messages', 'MessagesController@getMessages');
Route::post('/contact/submit', 'MessagesController@submit');
/*
|-----------------
|   To-Do list
|-----------------
*/
Route::resource('todo', 'TodosController');
/*
|-----------------
|   Authentication
|-----------------
*/
Auth::routes();
/*
|-----------------
|   Companies listing
|-----------------
*/
Route::resource('listings', 'ListingsController');
Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
/*
|-----------------
|   PhotoGallery
|-----------------
*/
Route::get('/photoshow/albums', 'AlbumsController@index')->name('photoshow.index');
Route::get('/photoshow/albums/create', 'AlbumsController@create')->name('photoshow.create');
Route::get('/photoshow/albums/{id}', 'AlbumsController@show')->name('photoshow.show');
Route::post('/photoshow/albums/store', 'AlbumsController@store')->name('photoshow.store');
Route::get('/photoshow/photos/create/{id}', 'PhotosController@create');
Route::post('/photoshow/photos/store', 'PhotosController@store');
Route::get('/photoshow/photos/{id}', 'PhotosController@show');
Route::delete('/photoshow/photos/{id}', 'PhotosController@destroy');
/*
|-----------------
|   Api items
|-----------------
*/
Route::resource('api/items', 'ItemsController');

resources/views/inc/messages.blade.php
@if(count($errors) > 0)
    @foreach($errors->all() as $error)
        <div class="alert alert-danger">
            {{$error}}
        </div>
    @endforeach
@endif

@if(session('success'))
    <div class="alert alert-success">
        {{session('success')}}
    </div>
@endif

@if(session('error'))
    <div class="alert alert-danger">
        {{session('error')}}
    </div>
@endif

resources/views/inc/navbar.blade.php
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Acme</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item {{Request::is('/') ? 'active' : ''}}">
                <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item {{Request::is('about') ? 'active' : ''}}">
                <a class="nav-link" href="/about">About</a>
            </li>
            <li class="nav-item {{Request::is('contact') ? 'active' : ''}}">
                <a class="nav-link" href="/contact">Contact</a>
            </li>
            <li class="nav-item dropdown {{Request::is('todo') ? 'active' : ''}}">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">ToDo</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="/todo">List</a>
                    <a class="dropdown-item" href="/todo/create">Create ToDo</a>
                </div>
            </li>
            <li class="nav-item dropdown {{Request::is('photoshow') ? 'active' : ''}}">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown02" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Photoshow</a>
                <div class="dropdown-menu" aria-labelledby="dropdown02">
                    <a class="dropdown-item" href="/photoshow/albums">Albums</a>
                    <a class="dropdown-item" href="/photoshow/albums/create">Create Album</a>
                </div>
            </li>
            <li class="nav-item {{Request::is('api/items') ? 'active' : ''}}">
                <a class="nav-link" href="/api/items">API Items</a>
            </li>
        </ul>

        <!-- Right Side Of Navbar -->
        <ul class="navbar-nav ml-auto">
            <!-- Authentication Links -->
            @guest
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                </li>
                @if (Route::has('register'))
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                    </li>
                @endif
            @else
                <li class="nav-item dropdown">
                    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                        {{ Auth::user()->name }} <span class="caret"></span>
                    </a>

                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{{ route('dashboard') }}">Dashboard</a>
                        <a class="dropdown-item" href="{{ route('listings.index') }}">Listings</a>
                        <a class="dropdown-item" href="{{ route('logout') }}"
                           onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                            {{ __('Logout') }}
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </div>
                </li>
            @endguest
        </ul>
    </div>
</nav>

resources/views/inc/showcase.blade.php
<div class="jumbotron text-center">
    <div class="container">
        <h1>welcome to our Site</h1>
        <p class="lead">Welcome to our brand new laravel powered website. This site uses Laravel 5.7</p>
    </div>
</div>

resources/views/inc/sidebar.blade.php
@section('sidebar')
    <div class="well">
        <h3>Sidebar</h3>
        This is the sidebar
    </div>
    @show